# https://hub.docker.com/r/multiarch/debian-debootstrap/

language: generic

sudo: required

services: docker

env:
  global: VERSION=stretch

matrix:
  include:
    - env:
      - ARCH=amd64
      - NATIVE=True
    - env:
      - ARCH=i386
      - NATIVE=True
    - env: ARCH=ppc64el
    - env: ARCH=mipsel
    - env: ARCH=mips
    - env: ARCH=armhf
    - env: ARCH=armel
    - env: ARCH=arm64

git:
  depth: 1

## Installing a newer Docker version
#addons:
#  apt:
#    packages:
#      - docker-ce

install:
  # May be skip for i386 and amd64
  - if [ -z "$NATIVE" ]; then docker run --privileged multiarch/qemu-user-static:register --reset; fi
  - docker pull multiarch/debian-debootstrap:"$ARCH"-"$VERSION"

before_script:
  # Dirty fix https://github.com/multiarch/qemu-user-static/issues/15
  - sudo echo -1 > /proc/sys/fs/binfmt_misc/qemu-mipsn32
  - sudo echo -1 > /proc/sys/fs/binfmt_misc/qemu-mipsn32el

script:
  - docker run -v $(pwd):/workd -w /workd -it multiarch/debian-debootstrap:"$ARCH"-"$VERSION" bash /workd/entrypoint.sh

after_script:
  - ls -lh
